language: python
python:
    - "nightly"
    - '3.6-dev'
    - 3.5
    - 3.4
    - 3.3
    - 2.7
sudo: false
before_install:
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
    
install:
    - pip install -U setuptools
    - pip install -f travis-wheels/wheelhouse -e .[test] codecov
    - python -c 'import ipykernel.kernelspec; ipykernel.kernelspec.install(user=True)'
script:
    - nosetests -v --with-coverage --cover-package jupyter_client jupyter_client
after_success:
    - codecov
matrix:
    allow_failures:
        - python: nightly
